-
    name: Set password
    hosts: all
    become: yes
    vars:
      admin_pass: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"
      splynx_pass: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"

    tasks:
      -
        name: set&output splynx password
        shell: /var/www/splynx/system/script/passwd admin --login=splynx --password={{splynx_pass}}
        register: result_splynx
      -
        name: set&output admin password
        shell: /var/www/splynx/system/script/passwd admin --login=admin --password={{admin_pass}}
        register: result_admin

      - debug:
          msg:
            - "{{ result_splynx.stdout}}"
            - "{{ result_admin.stdout}}"
