-
    name: New server. Copy&replace Splynx files
    hosts: splynx
    become: yes
    vars:
        splynx_folder: "/var/www/test_splynx/"      #with first "/" and without last "/"
        backup_files: "/tmp/migrate-files"  #with first "/" and without last "/"

    tasks:
        -
            name: 'move addons, templates, uploads folders'
            copy:
              src: "{{backup_files}}/{{item}}"
              dest: "{{splynx_folder}}"
              remote_src: yes
              owner: splynx
              group: splynx
            loop:
              - addons
              - templates
              - uploads
